### ISSUE TITLE
Error inflating class com.kevalpatel.passcodeview.PinView

### ISSUE THREAD

**Issue by praveenb** [kevalpatel2106/PasscodeView#10]
Hi @kevalpatel2106 ,

I see below error on a device with Fingerprint scanner on rear side

```
Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.kevalpatel.passcodeview.PinView
Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.kevalpatel.passcodeview.PinView
Caused by: java.lang.reflect.InvocationTargetException
.....
.....
......
**Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Paint.setColor(int)' on a null object reference**
at com.kevalpatel.passcodeview.BoxFingerprint.onFingerprintAuthFailed(BoxFingerprint.java:163)
at com.kevalpatel.passcodeview.FingerPrintAuthHelper.cipherInit(FingerPrintAuthHelper.java:207)
at com.kevalpatel.passcodeview.FingerPrintAuthHelper.getCryptoObject(FingerPrintAuthHelper.java:241)
at com.kevalpatel.passcodeview.FingerPrintAuthHelper.startAuth(FingerPrintAuthHelper.java:258)
at com.kevalpatel.passcodeview.BoxFingerprint.init(BoxFingerprint.java:76)
at com.kevalpatel.passcodeview.BoxFingerprint.<init>(BoxFingerprint.java:68)
at com.kevalpatel.passcodeview.PasscodeView.init(PasscodeView.java:109)
at com.kevalpatel.passcodeview.PasscodeView.<init>(PasscodeView.java:72)
at com.kevalpatel.passcodeview.PinView.<init>(PinView.java:70)
```
I see this issue happening `mFingerPrintAuthHelper.startAuth()` method called in  `BoxFingerprint ` when Failed to generate secrete key for authentication. Then its calling this onFingerprintAuthFailed().
Here `mStatusTextPaint` not initialized yet in code. So causing app crash.

Thank you.

**Comment by kevalpatel2106** [comment]
@praveenb What's the name of the device? Also, please provide the code where you are defining PinView in XML and Java code.

**Comment by praveenb** [comment]
Model is Vernee Mix 2, Nougat (7.0v)
And I debug code, I see this exception
`java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use
`
Thank you.

**Comment by praveenb** [comment]
@kevalpatel2106 , I added a new Fingerprint on that device then I see no crash with Pinview. And app able to recognize Fingerprint.

But anyhow, This crash needs to fix when this above exception occurred on a device. 

Just FYI, I just want give suggestion about the fix could be, In `BoxFingerprint ` class, call `preparePaint()` method in init method as below
```
 private void init() {
        preparePaint(); //this line fixes the crash issue
        isFingerPrintBoxVisible = Utils.isFingerPrintEnrolled(getContext());

        if (isFingerPrintBoxVisible) {
            mFingerPrintAuthHelper = new FingerPrintAuthHelper(getContext(), this);
            mFingerPrintAuthHelper.startAuth();
        }
    }
```

I think you may know a better way to fix it. Please fix it and release a new version, helps a lot.

Below is my code
In XML 
```
<LinearLayout
        android:id="@+id/pinLockLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="top|center_horizontal"
        android:orientation="vertical"
        android:padding="@dimen/spacing_20"
        android:visibility="visible"
        android:weightSum="2">

        <com.kevalpatel.passcodeview.PinView
            android:id="@+id/pin_view"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="2"
            app:dividerColor="@color/colorPrimaryDark"
            app:fingerprintDefaultText="Scan your finger to unlock application"
            app:fingerprintEnable="true"
            app:fingerprintTextColor="@color/white"
            app:fingerprintTextSize="@dimen/size_24"
            app:giveTactileFeedback="true"
            app:pin_titleText="@string/enter_pin"
            app:pin_titleTextColor="@color/white"
            app:titleTextColor="@android:color/white"/>

        <TextView
            android:id="@+id/tvEnterPassword"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="right"
            android:gravity="right"
            android:padding="@dimen/spacing_10"
            android:text="@string/enter_password"
            android:textAppearance="@android:style/TextAppearance.Small"
            android:textColor="@drawable/text_selector_gray_cyan"
            android:visibility="visible"/>
    </LinearLayout>
```
in Java file

```
private void initPinView(){
        mPinView.setCorrectPin(getPinArray());
        //Build the desired key shape and pass the theme parameters.
        //REQUIRED
        mPinView.setKey(new RoundKey.Builder(mPinView)
                .setKeyPadding(R.dimen.key_padding)
                .setKeyStrokeColorResource(R.color.tab_gray)
                .setKeyStrokeWidth(R.dimen.key_stroke_width)
                .setKeyTextColorResource(R.color.tab_gray)
                .setKeyTextSize(R.dimen.key_text_size)
                .build());

        //Build the desired indicator shape and pass the theme attributes.
        //REQUIRED
        mPinView.setIndicator(new CircleIndicator.Builder(mPinView)
                .setIndicatorRadius(R.dimen.indicator_radius)
                .setIndicatorFilledColorResource(R.color.sl_blue)
                .setIndicatorStrokeColorResource(R.color.tab_gray)
                .setIndicatorStrokeWidth(R.dimen.indicator_stroke_width)
                .build());

        //Set the name of the keys based on your locale.
        //OPTIONAL. If not passed key names will be displayed based on english locale.
        mPinView.setKeyNames(new KeyNamesBuilder()
                .setKeyOne(this, R.string.key_1)
                .setKeyTwo(this, R.string.key_2)
                .setKeyThree(this, R.string.key_3)
                .setKeyFour(this, R.string.key_4)
                .setKeyFive(this, R.string.key_5)
                .setKeySix(this, R.string.key_6)
                .setKeySeven(this, R.string.key_7)
                .setKeyEight(this, R.string.key_8)
                .setKeyNine(this, R.string.key_9)
                .setKeyZero(this, R.string.key_0));


        mPinView.setAuthenticationListener(new AuthenticationListener() {
            @Override
            public void onAuthenticationSuccessful() {
                //User authenticated successfully.
                //Navigate to secure screens.
                startMainActivity(false);
            }

            @Override
            public void onAuthenticationFailed() {

                mPinView.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        mPinView.invalidate();
                        mPinView.requestLayout();
                        Toast.makeText(LogonActivity.this, "Entered Invalid PIN", Toast.LENGTH_SHORT).show();
                    }
                }, 100);
            }
        });
    }
```
Please let me know, your suggestions on it.

Thank you.

**Comment by praveenb** [comment]
Hi @kevalpatel2106 ,

Could you please fix this crash issue which is happening when exception `java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use` 

Since the crash is happening in library, fix should be apply in library. I'm not able to apply fix in my app side. Please fix and release a new version.

Looking forward for your reply.

Thank you.

**Comment by kevalpatel2106** [comment]
@praveenb Hi, 👋 I looked into your code. Why are you invalidating the view manually in `onAuthenticationFailed()`? The view will invalidate itself whenever the authentication fails after playing all the error animations.

**Comment by kevalpatel2106** [comment]
@praveenb Can you generate new issue regarding `java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use`?

**Comment by praveenb** [comment]
Hi @kevalpatel2106 , 

I applied invalidate view code to fix another issue #3, Kindly see the comment i posted in that link.
I'm sure crash happening at the time of setContentView in my Activity when inflating XML Pinview. Crash not when app tries to Authenticate user entered pinview. Please see the crash report below

```
Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.kevalpatel.passcodeview.PinView
Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.kevalpatel.passcodeview.PinView
```

Kindly let me know on it.
Thank you.

**Comment by praveenb** [comment]
I fork the library and Applied fix for crash issue updated in Jit pack.
implementation 'com.github.praveenb:passcodeview:1.2.2v'

Hope it helps somebody.
Thank you.

**Comment by kevalpatel2106** [comment]
@praveenb can you generate PR for the fix instead of creating new fork?

**Comment by praveenb** [comment]
Hi @kevalpatel2106 ,

I deleted bintray.gradle (since i'm not sure to use it at moment) and also will apply few minor changes in forked library as per other requirement.

So, I think PR is not a good idea for this. But to handle crash issue, I just applied one line change in code 
In `BoxFingerprint `class, call `preparePaint()` method in init method as below 

```
private void init() {
        preparePaint(); //this line fixes the crash issue
        isFingerPrintBoxVisible = Utils.isFingerPrintEnrolled(getContext());

        if (isFingerPrintBoxVisible) {
            mFingerPrintAuthHelper = new FingerPrintAuthHelper(getContext(), this);
            mFingerPrintAuthHelper.startAuth();
        }
    }
```

Hope it helps.
That's it,
Thank you.
