### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by Avinashahex** [kevalpatel2106/PasscodeView#13]
java.lang.NullPointerException: Set key using KeyBuilder first.
	at com.kevalpatel.passcodeview.internal.BoxKeypad.measureView(BoxKeypad.java:155)
	at com.kevalpatel.passcodeview.PinView.measureView(PinView.java:182)
	at com.kevalpatel.passcodeview.internal.BasePasscodeView.onMeasure_Original(BasePasscodeView.java:212)
	at com.kevalpatel.passcodeview.internal.BasePasscodeView.onMeasure(BasePasscodeView.java)
	at android.view.View.measure_Original(View.java:22071)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:22035)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure_Original(View.java:22071)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:22035)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6602)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
	at android.view.View.measure_Original(View.java:22071)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:22035)
	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
	at android.view.View.measure_Original(View.java:22071)
	at android.view.View_Delegate.measure(View_Delegate.java:80)
	at android.view.View.measure(View.java:22035)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.measureView(RenderSessionImpl.java:590)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:343)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:544)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:678)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kevalpatel2106** [comment]
@Avinashahex Can you post the code on how you are building your pin view? I think you are missing the [step](https://github.com/kevalpatel2106/PasscodeView/wiki/PinView-Setup#set-the-shape-of-the-pin-indicators-you-want-to-use) to add the key builder.

**Comment by Avinashahex** [comment]
Rendering issue is there when I am using pinview in xml.

**Comment by kevalpatel2106** [comment]
@Avinashahex Can you post your XML file and the java code for setting pin view. Keep in mind even if you use an XML file, you need to set PinView in your activity/fragment according to readme.

**Comment by Avinashahex** [comment]
Ok.
I have set the Pinview via java code its working fine, but I am not getting how to change color of invalid passcode indicator and finger scan. And can U confirm when the Dynamic pin integration can be implemented.
