### ISSUE TITLE
PatternView

### ISSUE THREAD

**Issue by BichCNTT** [kevalpatel2106/PasscodeView#17]
When I click in one point Pattern Activity will crash. How can I fix that?

**Comment by kevalpatel2106** [comment]
@BichCNTT Can you share me the crash log and the recorded crash video if possible? I am not able to reproduce.

**Comment by Shruthyshanthraj** [comment]
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.kevalpatel.passcodeview.authenticator.PasscodeViewPatternAuthenticator.isValidPattern(PasscodeViewPatternAuthenticator.java:45)

**Comment by Shruthyshanthraj** [comment]
Hi Patel can you please help me out with this bug and also indicator by default is not displayed , after pin entered it is displayed, but in the image in the blog the indicators are present by default with stroke. Please help me out.

     Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.kevalpatel.passcodeview.authenticator.PasscodeViewPatternAuthenticator.isValidPattern(PasscodeViewPatternAuthenticator.java:45)
